name: Docker Image

on:
  push:
    paths:
      - "Sources/**"
      - ".github/workflows/docker-image.yaml"
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: check repository
        uses: actions/checkout@v4
        with:
          lfs: "true"
          fetch-depth: 0

      - name: install and calculate version
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"

      - name: determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: Sources
          push: true
          tags: |
            bvdcode/cotton:latest
            bvdcode/cotton:${{ steps.gitversion.outputs.semVer }}
          file: Sources/Cotton.Server/Dockerfile

      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: Sources
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cotton:latest
            ghcr.io/${{ github.repository_owner }}/cotton:${{ steps.gitversion.outputs.semVer }}
          file: Sources/Cotton.Server/Dockerfile

      #Create release
      - name: Create Release
        if: 1 == 0 #needs.build.outputs.CommitsSinceVersionSource > 0 #Only release if there has been a commit/version change
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.Version }}
          release_name: Release ${{ needs.build.outputs.Version }}
      - name: Create Release
        if: needs.build.outputs.CommitsSinceVersionSource > 0 #Only release if there has been a commit/version change
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.Version }}
          name: Release ${{ needs.build.outputs.Version }}
          artifacts: "nupkg/*"
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
