name: Docker Image

env:
  IMAGE_NAME: cotton
  CONTEXT_PATH: Sources
  SOURCES_PATH: Cotton.Server

on:
  push:
    paths:
      - "Sources/**"
      - ".github/workflows/docker-image.yaml"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: check repository
        uses: actions/checkout@v4
        with:
          lfs: "true"
          fetch-depth: 0

      - name: install and calculate version
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"

      - name: determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT_PATH }}
          push: true
          tags: |
            bvdcode/${{ env.IMAGE_NAME }}:latest
            bvdcode/${{ env.IMAGE_NAME }}:${{ steps.gitversion.outputs.semVer }}
          file: ${{ env.CONTEXT_PATH }}/${{ env.SOURCES_PATH }}/Dockerfile

      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT_PATH }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.gitversion.outputs.semVer }}
          file: ${{ env.CONTEXT_PATH }}/${{ env.SOURCES_PATH }}/Dockerfile

      - name: Create Release
        if: needs.build.outputs.CommitsSinceVersionSource > 0
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gitversion.outputs.semVer }}
          name: Release ${{ steps.gitversion.outputs.semVer }}
          artifacts: "nupkg/*"
          token: ${{ secrets.GITHUB_TOKEN }}
